name = "spark_unbound"
description = "Unbound data structures in Ada-Spark"
version = "0.1.1"

authors = ["Manuel Hatzl"]
maintainers = ["Manuel Hatzl <hatzlmanuel@outlook.com>"]
maintainers-logins = ["mhatzl"]
