name = "spark_unbound"
description = "Unbound data structures in Ada-Spark"
version = "0.1.2"

authors = ["Manuel Hatzl"]
maintainers = ["Manuel Hatzl <hatzlmanuel@outlook.com>"]
maintainers-logins = ["mhatzl"]
website = "https://github.com/mhatzl/spark_unbound"

licenses = "GPL-3.0-or-later"

tags = ["spark", "unbound"]
